# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    data_collector.tasks:
        class: AppBundle\Collector\TaskDataCollector
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: data_collector, template: 'collectors/tasks.html.twig', id: 'tasks' }

